export default {

    getBreedOfDogs() {
        return [
            { text: 'Afghan Hound', value: 'afghanhound'},
            { text: 'Airedale Terrier', value: 'airedaleterrier'},
            { text: 'Akbash', value: 'Akbash'},
            { text: 'Akita', value: 'Akita'},
            { text: 'Alaskan Malamute', value: 'alaskanmalamute'},
            { text: 'American Bulldog', value: 'americanbulldog'},
            { text: 'American Bully', value: 'americanbully'},
            { text: 'American Eskimo Dog', value: 'americaneskimodog'},
            { text: 'American Foxhound', value: 'americanfoxhound'},
            { text: 'American Hairless Terrier', value: 'americanhairlessterrier'},
            { text: 'American Staffordshire Terrier', value: 'americanstaffordshireterrier'},
            { text: 'American Water Spaniel', value: 'americanwaterspaniel'},
            { text: 'Anatolian Shepherd', value: 'anatolianshepherd'},
            { text: 'Appenzell Mountain Dog', value: 'appenzellmountaindog'},
            { text: 'Aussiedoodle', value: 'aussiedoodle'},
            { text: 'Australian Cattle Dog / Blue Heeler', value: 'australiancattledogblueheeler'},
            { text: 'Australian Kelpie', value: 'australiankelpie'},
            { text: 'Australian Shepherd', value: 'australianshepherd'},
            { text: 'Australian Terrier', value: 'australianterrier'},
            { text: 'Basenji', value: 'basenji'},
            { text: 'Basset Hound', value: 'bassethound'},
            { text: 'Beagle', value: 'beagle'},
            { text: 'Bearded Collie', value: 'beardedcollie'},
            { text: 'Beauceron', value: 'beauceron'},
            { text: 'Bedlington Terrier', value: 'bedlingtonterrier'},
            { text: 'Belgian Shepherd / Laekenois', value: 'belgianshepherdlaekenois'},
            { text: 'Belgian Shepherd / Malinois', value: 'belgianshepherdmalinois'},
            { text: 'Belgian Shepherd / Sheepdog', value: 'belgianshepherdsheepdog'},
            { text: 'Belgian Shepherd / Tervuren', value: 'belgianshepherdtervuren'},
            { text: 'Bernedoodle', value: 'bernedoodle'},
            { text: 'Bernese Mountain Dog', value: 'bernesemountaindog'},
            { text: 'Bichon Frise', value: 'bichonfrise'},
            { text: 'Black and Tan Coonhound', value: 'blackandtancoonhound'},
            { text: 'Black Labrador Retriever', value: 'blacklabradorretriever'},
            { text: 'Black Mouth Cur', value: 'blackmouthcur'},
            { text: 'Bloodhound', value: 'bloodhound'},
            { text: 'Blue Lacy', value: 'bluelacy'},
            { text: 'Bluetick Coonhound', value: 'bluetickvoonhound'},
            { text: 'Boerboel', value: 'boerboel'},
            { text: 'Bolognese', value: 'bolognese'},
            { text: 'Border Collie', value: 'bordercollie'},
            { text: 'Border Terrier', value: 'borderterrier'},
            { text: 'Borzoi', value: 'borzoi'},
            { text: 'Boston Terrier', value: 'bostonterrier'},
            { text: 'Bouvier des Flandres', value: 'bouvierdesflandres'},
            { text: 'Boxer', value: 'boxer'},
            { text: 'Boykin Spaniel', value: 'boykinspaniel'},
            { text: 'Briard', value: 'briard'},
            { text: 'Brittany Spaniel', value: 'brittanyspaniel'},
            { text: 'Brussels Griffon', value: 'brusselsgriffon'},
            { text: 'Bull Terrier', value: 'bullterrier'},
            { text: 'Bullmastiff', value: 'bullmastiff'},
            { text: 'Cairn Terrier', value: 'cairnterrier'},
            { text: 'Canaan Dog', value: 'Canaan Dog'},
            { text: 'Cane Corso', value: 'canecorso'},
            { text: 'Cardigan Welsh Corgi', value: 'cardiganwelshcorgi'},
            { text: 'Carolina Dog', value: 'carolinadog'},
            { text: 'Catahoula Leopard Dog', value: 'catahoulaleoparddog'},
            { text: 'Cattle Dog', value: 'cattledog'},
            { text: 'Caucasian Sheepdog / Caucasian Ovtcharka', value: 'caucasiansheepdogcaucasianovtcharka'},
            { text: 'Cavalier King Charles Spaniel', value: 'cavalierkingcharlesspaniel'},
            { text: 'Cavapoo', value: 'cavapoo'},
            { text: 'Chesapeake Bay Retriever', value: 'chesapeakebayretriever'},
            { text: 'Chihuahua', value: 'chihuahua'},
            { text: 'Chinese Crested Dog', value: 'chinesecresteddog'},
            { text: 'Chinese Foo Dog', value: 'chinesefoodog'},
            { text: 'Chinook', value: 'chinook'},
            { text: 'Chiweenie', value: 'chiweenie'},
            { text: 'Chocolate Labrador Retriever', value: 'chocolatelabradorretriever'},
            { text: 'Chow Chow', value: 'chowchow'},
            { text: 'Cirneco dell Etna', value: 'cirnecodelletna'},
            { text: 'Clumber Spaniel', value: 'clumberspaniel'},
            { text: 'Cockapoo', value: 'cockapoo'},
            { text: 'Cocker Spaniel', value: 'cockerspaniel'},
            { text: 'Collien', value: 'collie'},
            { text: 'Coonhound', value: 'coonhound'},
            { text: 'Corgi', value: 'corgi'},
            { text: 'Coton de Tulear', value: 'Coton de Tulear'},
            { text: 'Curly-Coated Retriever', value: 'curlycoatedretriever'},
            { text: 'Dachshund', value: 'dachshund'},
            { text: 'Dalmatian', value: 'dalmatian'},
            { text: 'Dandie Dinmont Terrier', value: 'dandiedinmontterrier'},
            { text: 'Doberman Pinscher', value: 'dobermanpinscher'},
            { text: 'Dogo Argentino', value: 'dogoargentino'},
            { text: 'Dogue de Bordeaux', value: 'doguedebordeaux'},
            { text: 'Dutch Shepherd', value: 'dutchshepherd'},
            { text: 'English Bulldog', value: 'englishbulldog'},
            { text: 'English Cocker Spaniel', value: 'englishcockerspaniel'},
            { text: 'English Coonhound', value: 'englishcoonhound'},
            { text: 'English Foxhound', value: 'englishfoxhound'},
            { text: 'English Pointer', value: 'englishpointer'},
            { text: 'English Setter', value: 'englishsetter'},
            { text: 'English Shepherd', value: 'englishshepherd'},
            { text: 'English Springer Spaniel', value: 'englishspringerspaniel'},
            { text: 'English Toy Spaniel', value: 'englishtoyspaniel'},
            { text: 'Eskimo Dog', value: 'eskimodog'},
            { text: 'Feist', value: 'feist'},
            { text: 'Field Spaniel', value: 'fieldspaniel'},
            { text: 'Fila Brasileiro', value: 'filabrasileiro'},
            { text: 'Finnish Lapphund', value: 'finnishlapphund'},
            { text: 'Finnish Spitz', value: 'finnishppitz'},
            { text: 'Flat-Coated Retriever', value: 'flatcoatedretriever'},
            { text: 'Fox Terrier', value: 'foxterrier'},
            { text: 'Foxhound', value: 'foxhound'},
            { text: 'French Bulldog', value: 'frenchbulldog'},
            { text: 'Galgo Spanish Greyhound', value: 'galgospanishgreyhound'},
            { text: 'German Pinscher', value: 'germanpinscher'},
            { text: 'German Shepherd Dog', value: 'germanshepherddog'},
            { text: 'German Shorthaired Pointer', value: 'germanshorthairedpointer'},
            { text: 'German Spitz', value: 'germanspitz'},
            { text: 'German Wirehaired Pointer', value: 'germanwirehairedpointer'},
            { text: 'Giant Schnauzer', value: 'giantschnauzer'},
            { text: 'Glen of Imaal Terrier', value: 'glenofimaalterrier'},
            { text: 'Golden Retriever', value: 'goldenretriever'},
            { text: 'Goldendoodle', value: 'Goldendoodle'},
            { text: 'Gordon Setter', value: 'gordonsetter'},
            { text: 'Great Dane', value: 'greatdane'},
            { text: 'Great Pyrenees', value: 'greatpyrenees'},
            { text: 'Greater Swiss Mountain Dog', value: 'greaterswissmountaindog'},
            { text: 'Greyhound', value: 'greyhound'},
            { text: 'Hamiltonstovare', value: 'hamiltonstovare'},
            { text: 'Harrier', value: 'harrier'},
            { text: 'Havanese', value: 'Havanese'},
            { text: 'Hound', value: 'hound'},
            { text: 'Hovawart', value: 'hovawart'},
            { text: 'Husky', value: 'husky'},
            { text: 'Ibizan Hound', value: 'ibizanhound'},
            { text: 'Icelandic Sheepdog', value: 'icelandicsheepdog'},
            { text: 'Illyrian Sheepdog', value: 'illyriansheepdog'},
            { text: 'Irish Setter', value: 'irishsetter'},
            { text: 'Irish Terrier', value: 'irishterrier'},
            { text: 'Irish Water Spaniel', value: 'irishwaterspaniel'},
            { text: 'Irish Wolfhound', value: 'irishwolfhound'},
            { text: 'Italian Greyhound', value: 'italiangreyhound'},
            { text: 'Jack Russell Terrier', value: 'jackrussellterrier'},
            { text: 'Japanese Chin', value: 'japanesechin'},
            { text: 'Jindo', value: 'Jindo'},
            { text: 'Kai Dog', value: 'kaidog'},
            { text: 'Karelian Bear Dog', value: 'karelianbeardog'},
            { text: 'Keeshond', value: 'keeshond'},
            { text: 'Kerry Blue Terrier', value: 'kerryblueterrier'},
            { text: 'Kishu', value: 'kishu'},
            { text: 'Klee Kai', value: 'kleekai'},
            { text: 'Komondor', value: 'komondor'},
            { text: 'Kuvasz', value: 'kuvasz'},
            { text: 'Kyi Leo', value: 'kyileo'},
            { text: 'Labradoodle', value: 'labradoodle'},
            { text: 'Labrador Retriever', value: 'labradorretriever'},
            { text: 'Lakeland Terrier', value: 'lakelandterrier'},
            { text: 'Lancashire Heeler', value: 'lancashireheeler'},
            { text: 'Leonberger', value: 'leonberger'},
            { text: 'Lhasa Apso', value: 'lhasaapso'},
            { text: 'Lowchen', value: 'lowchen'},
            { text: 'Lurcher', value: 'lurcher'},
            { text: 'Maltese', value: 'maltese'},
            { text: 'Maltipoo', value: 'maltipoo'},
            { text: 'Manchester Terrier', value: 'manchesterterrier'},
            { text: 'Maremma Sheepdog', value: 'maremmasheepdog'},
            { text: 'Mastiff', value: 'Mastiff'},
            { text: 'McNab', value: 'mcnab'},
            { text: 'Miniature Bull Terrier', value: 'miniaturebullterrier'},
            { text: 'Miniature Dachshund', value: 'miniaturedachshund'},
            { text: 'Miniature Pinscher', value: 'miniaturepinscher'},
            { text: 'Miniature Poodle', value: 'miniaturepoodle'},
            { text: 'Miniature Schnauzer', value: 'miniatureschnauzer'},
            { text: 'Mixed Breed', value: 'mixedbreed'},
            { text: 'Morkie', value: 'morkie'},
            { text: 'Mountain Cur', value: 'mountaincur'},
            { text: 'Mountain Dog', value: 'mountaindog'},
            { text: 'Munsterlander', value: 'munsterlander'},
            { text: 'Neapolitan Mastiff', value: 'neapolitanmastiff'},
            { text: 'New Guinea Singing Dog', value: 'newguineasingingdog'},
            { text: 'Newfoundland Dog', value: 'newfoundlanddog'},
            { text: 'Norfolk Terrier', value: 'norfolkterrier'},
            { text: 'Norwegian Buhund', value: 'norwegianbuhund'},
            { text: 'Norwegian Elkhound', value: 'norwegianelkhound'},
            { text: 'Norwegian Lundehund', value: 'norwegianlundehund'},
            { text: 'Norwich Terrier', value: 'Norwich Terrier'},
            { text: 'Nova Scotia Duck Tolling Retriever', value: 'novascotiaducktollingretriever'},
            { text: 'Old English Sheepdog', value: 'oldenglishsheepdog'},
            { text: 'Otterhound', value: 'otterhound'},
            { text: 'Papillon', value: 'papillon'},
            { text: 'Parson Russell Terrier', value: 'parsonrssellterrier'},
            { text: 'Patterdale Terrier / Fell Terrier', value: 'patterdaleterrierfellterrier'},
            { text: 'Pekingese', value: 'Ppekingese'},
            { text: 'Pembroke Welsh Corgi', value: 'pembrokewelshcorgi'},
            { text: 'Peruvian Inca Orchid', value: 'peruvianincaorchid'},
            { text: 'Petit Basset Griffon Vendeen', value: 'petitbassetgriffonvendeen'},
            { text: 'Pharaoh Hound', value: 'pharaohhound'},
            { text: 'Pit Bull Terrier', value: 'pitbullterrier'},
            { text: 'Plott Hound', value: 'plotthound'},
            { text: 'Pointer', value: 'Pointer'},
            { text: 'Polish Lowland Sheepdog', value: 'polishlowlandsheepdog'},
            { text: 'Pomeranian', value: 'pomeranian'},
            { text: 'Pomsky', value: 'pomsky'},
            { text: 'Poodle', value: 'poodle'},
            { text: 'Portuguese Podengo', value: 'portuguesepodengo'},
            { text: 'Portuguese Water Dog', value: 'portuguesewaterdog'},
            { text: 'Presa Canario', value: 'presacanario'},
            { text: 'Pug', value: 'pug'},
            { text: 'Puggle', value: 'puggle'},
            { text: 'Puli', value: 'puli'},
            { text: 'Pumi', value: 'pumi'},
            { text: 'Pyrenean Shepherd', value: 'pyreneanshepherd'},
            { text: 'Rat Terrier', value: 'ratterrier'},
            { text: 'Redbone Coonhound', value: 'redbonecoonhound'},
            { text: 'Retriever', value: 'retriever'},
            { text: 'Rhodesian Ridgeback', value: 'rhodesianridgeback'},
            { text: 'Rottweiler', value: 'rottweiler'},
            { text: 'Rough Collie', value: 'roughcollie'},
            { text: 'Saint Bernard', value: 'saintbernard'},
            { text: 'Saluki', value: 'saluki'},
            { text: 'Samoyed', value: 'samoyed'},
            { text: 'Sarplaninac', value: 'sarplaninac'},
            { text: 'Schipperke', value: 'schipperke'},
            { text: 'Schnauzer', value: 'schnauzer'},
            { text: 'Schnoodle', value: 'schnoodle'},
            { text: 'Scottish Deerhound', value: 'scottishdeerhound'},
            { text: 'Scottish Terrier', value: 'scottishterrier'},
            { text: 'Sealyham Terrier', value: 'sealyhamterrier'},
            { text: 'Setter', value: 'setter'},
            { text: 'Shar-Pei', value: 'shar-pei'},
            { text: 'Sheep Dog', value: 'sheepdog'},
            { text: 'Sheepadoodle', value: 'sheepadoodle'},
            { text: 'Shepherd', value: 'shepherd'},
            { text: 'Shetland Sheepdog / Sheltie', value: 'shetlandsheepdogsheltie'},
            { text: 'Shiba Inu', value: 'shibainu'},
            { text: 'Shih poo', value: 'shihpoo'},
            { text: 'Shih Tzu', value: 'shihtzu'},
            { text: 'Shollie', value: 'shollie'},
            { text: 'Siberian Husky', value: 'siberianhusky'},
            { text: 'Silky Terrier', value: 'silkyterrier'},
            { text: 'Skye Terrier', value: 'skyeterrier'},
            { text: 'Sloughi', value: 'sloughi'},
            { text: 'Smooth Collie', value: 'smoothcollie'},
            { text: 'Smooth Fox Terrier', value: 'smoothfoxterrier'},
            { text: 'South Russian Ovtcharka', value: 'southrussianovtcharka'},
            { text: 'Spaniel', value: 'spaniel'},
            { text: 'Spanish Water Dog', value: 'spanishwaterdog'},
            { text: 'Spinone Italiano', value: 'spinoneitaliano'},
            { text: 'Spitz', value: 'spitz'},
            { text: 'Staffordshire Bull Terrier', value: 'staffordshirebullterrier'},
            { text: 'Standard Poodle', value: 'standardpoodle'},
            { text: 'Standard Schnauzer', value: 'standardschnauzer'},
            { text: 'Sussex Spaniel', value: 'sussexspaniel'},
            { text: 'Swedish Vallhund', value: 'swedishvallhund'},
            { text: 'Tennessee Treeing Brindle', value: 'tennesseetreeingbrindle'},
            { text: 'Terrier', value: 'terrier'},
            { text: 'Thai Ridgeback', value: 'thairidgeback'},
            { text: 'Tibetan Mastiff', value: 'tibetanmastiff'},
            { text: 'Tibetan Spaniel', value: 'tibetanspaniel'},
            { text: 'Tibetan Terrier', value: 'tibetanterrier'},
            { text: 'Tosa Inu', value: 'tosainu'},
            { text: 'Toy Fox Terrier', value: 'toyfoxterrier'},
            { text: 'Toy Manchester Terrier', value: 'toymanchesterterrier'},
            { text: 'Treeing Walker Coonhound', value: 'treeingwalkercoonhound'},
            { text: 'Vizsla', value: 'vizsla'},
            { text: 'Weimaraner', value: 'Weimaraner'},
            { text: 'Welsh Springer Spaniel', value: 'welshspringerspaniel'},
            { text: 'Welsh Terrier', value: 'welshterrier'},
            { text: 'West Highland White Terrier / Westie', value: 'westhighlandwhiteterrierwestie'},
            { text: 'Wheaten Terrier', value: 'wheatenterrier'},
            { text: 'Whippet', value: 'whippet'},
            { text: 'White German Shepherd', value: 'whitegermanshepherd'},
            { text: 'Wire Fox Terrier', value: 'wirefoxterrier'},
            { text: 'Wirehaired Dachshund', value: 'wirehaireddachshund'},
            { text: 'Wirehaired Pointing Griffon', value: 'wirehairedpointinggriffon'},
            { text: 'Wirehaired Terrier', value: 'wirehairedterrier'},
            { text: 'Xoloitzcuintli / Mexican Hairless', value: 'xoloitzcuintlimexicanhairless'},
            { text: 'Yellow Labrador Retriever', value: 'yellowlabradorretriever'},
            { text: 'Yorkshire Terrier', value: 'yorkshireterrier'},
        ];
    },
    getBreedOfCats() {
        return [
            { text: 'Abyssinian', value: 'abyssinian'},
            { text: 'American Bobtail', value: 'americanbobtail'},
            { text: 'American Curl', value: 'americancurl'},
            { text: 'American Wirehair', value: 'americanwirehair'},
            { text: 'Applehead Siamese', value: 'appleheadsiamese'},
            { text: 'Balinese', value: 'balinese'},
            { text: 'Bengal', value: 'bengal'},
            { text: 'Birman', value: 'birman'},
            { text: 'Bombay', value: 'bombay'},
            { text: 'British Shorthair', value: 'britishshorthair'},
            { text: 'Burmese', value: 'burmese'},
            { text: 'Burmilla', value: 'burmilla'},
            { text: 'Calico', value: 'calico'},
            { text: 'Canadian Hairless', value: 'canadianhairless'},
            { text: 'Chartreux', value: 'hartreux'},
            { text: 'Chausie', value: 'chausie'},
            { text: 'Chinchilla', value: 'chinchilla'},
            { text: 'Cornish Rex', value: 'cornishrex'},
            { text: 'Cymric', value: 'cymric'},
            { text: 'Devon Rex', value: 'dilutecalico'},
            { text: 'Dilute Tortoiseshell', value: 'dilutetortoiseshell'},
            { text: 'Domestic Long Hair', value: 'Domestic Long Hair'},
            { text: 'Domestic Medium Hair', value: 'domesticmediumhair'},
            { text: 'Domestic Short Hair', value: 'domesticshorthair'},
            { text: 'Egyptian Mau', value: 'egyptianmau'},
            { text: 'Exotic Shorthair', value: 'exoticshorthair'},
            { text: 'Extra-Toes Cat / Hemingway Polydactyl', value: 'extratoescathemingwaypolydactyl'},
            { text: 'Havana', value: 'havana'},
            { text: 'Himalayan', value: 'himalayan'},
            { text: 'Japanese Bobtail', value: 'japanesebobtail'},
            { text: 'Javanese', value: 'javanese'},
            { text: 'Korat', value: 'korat'},
            { text: 'LaPerm', value: 'laperm'},
            { text: 'Maine Coon', value: 'mainecoon'},
            { text: 'Manx', value: 'manx'},
            { text: 'Nebelung', value: 'nebelung'},
            { text: 'Norwegian Forest Cat', value: 'norwegianforestcat'},
            { text: 'Ocicat', value: 'ocicat'},
            { text: 'Oriental Long Hair', value: 'orientallonghair'},
            { text: 'Oriental Short Hair', value: 'orientalshorthair'},
            { text: 'Oriental Tabby', value: 'orientaltabby'},
            { text: 'Persian', value: 'persian'},
            { text: 'Pixiebob', value: 'pixiebob'},
            { text: 'Ragamuffin', value: 'ragamuffin'},
            { text: 'Ragdoll', value: 'ragdoll'},
            { text: 'Russian Blue', value: 'russianblue'},
            { text: 'Scottish Fold', value: 'scottishfold'},
            { text: 'Selkirk Rex', value: 'selkirkrex'},
            { text: 'Siamese', value: 'siamese'},
            { text: 'Siberian', value: 'siberian'},
            { text: 'Silver', value: 'silver'},
            { text: 'Singapura', value: 'singapura'},
            { text: 'Snowshoe', value: 'snowshoe'},
            { text: 'Somali', value: 'somali'},
            { text: 'Sphynx / Hairless Cat', value: 'sphynxhairlesscat'},
            { text: 'Tabby', value: 'tabby'},
            { text: 'Tiger', value: 'tiger'},
            { text: 'Tonkinese', value: 'tonkinese'},
            { text: 'Torbie', value: 'torbie'},
            { text: 'Tortoiseshell', value: 'tortoiseshell'},
            { text: 'Toyger', value: 'toyger'},
            { text: 'Turkish Angora', value: 'turkishangora'},
            { text: 'Turkish Van', value: 'turkishvan'},
            { text: 'Tuxedo', value: 'tuxedo'},
            { text: 'York Chocolate', value: 'yorkchocolate'},
        ];
    },
    getBreedsofRabbits() {
        return [
            { text: 'American', value: 'american'},
            { text: 'American Fuzzy Lop', value: 'americanfuzzylop'},
            { text: 'American Sable', value: 'americansable'},
            { text: 'Angora Rabbit', value: 'angorarabbit'},
            { text: 'Belgian Hare', value: 'belgianhare'},
            { text: 'Beveren', value: 'beveren'},
            { text: 'Britannia Petite', value: 'britanniapetite'},
            { text: 'Bunny Rabbit', value: 'bunnyrabbit'},
            { text: 'Californian', value: 'californian'},
            { text: 'Champagne D Argent', value: 'champagnedargent'},
            { text: 'Checkered Giant', value: 'checkeredgiant'},
            { text: 'Chinchilla', value: 'chinchilla'},
            { text: 'Cinnamon', value: 'cinnamon'},
            { text: 'Creme D Argent', value: 'Cremedargent'},
            { text: 'Dutch', value: 'dutch'},
            { text: 'Dwarf', value: 'dwarf'},
            { text: 'Dwarf Eared', value: 'dwarfeared'},
            { text: 'English Lop', value: 'englishlop'},
            { text: 'English Spot', value: 'englishspot'},
            { text: 'Flemish Giant', value: 'flemishgiant'},
            { text: 'Florida White', value: 'floridawhite'},
            { text: 'French Lop', value: 'frenchlop'},
            { text: 'Havana', value: 'havana'},
            { text: 'Himalayan', value: 'himalayan'},
            { text: 'Holland Lop', value: 'hollandlop'},
            { text: 'Hotot', value: 'hotot'},
            { text: 'Jersey Wooly', value: 'jerseywooly'},
            { text: 'Lilac', value: 'lilac'},
            { text: 'Lionhead', value: 'lionhead'},
            { text: 'Lop Eared', value: 'lopeared'},
            { text: 'Mini Lop', value: 'minilop'},
            { text: 'Mini Rex', value: 'minirex'},
            { text: 'Netherland Dwarf', value: 'netherlanddwarf'},
            { text: 'Mini Rex', value: 'New Zealand'},
            { text: 'Palomino', value: 'palomino'},
            { text: 'Polish', value: 'polish'},
            { text: 'Rex', value: 'rex'},
            { text: 'Rhinelander', value: 'rhinelander'},
            { text: 'Satin', value: 'satin'},
            { text: 'Silver', value: 'silver'},
            { text: 'Silver Fox', value: 'silverfox'},
            { text: 'Silver Marten', value: 'silvermarten'},
            { text: 'Tan', value: 'tan'},
        ];
    },
    getBreedsofHorse() {
        return [
            { text: 'Appaloosa', value: 'appaloosa'},
            { text: 'Arabian', value: 'arabian'},
            { text: 'Belgian', value: 'belgian'},
            { text: 'Clydesdale', value: 'clydesdale'},
            { text: 'Connemara', value: 'connemara'},
            { text: 'Curly Horse', value: 'curlyhorse'},
            { text: 'Donkey', value: 'donkey'},
            { text: 'Draft', value: 'draft'},
            { text: 'Friesian', value: 'friesian'},
            { text: 'Gaited', value: 'gaited'},
            { text: 'Grade', value: 'grade'},
            { text: 'Haflinger', value: 'haflinger'},
            { text: 'Icelandic Horse', value: 'icelandichorse'},
            { text: 'Lipizzan', value: 'lipizzan'},
            { text: 'Miniature Horse', value: 'miniaturehorse'},
            { text: 'Missouri Foxtrotter', value: 'missourifoxtrotter'},
            { text: 'Morgan', value: 'morgan'},
            { text: 'Mule', value: 'mule'},
            { text: 'Mustang', value: 'mustang'},
            { text: 'Paint / Pinto', value: 'paintpinto'},
            { text: 'Palomino', value: 'palomino'},
            { text: 'Paso Fino', value: 'pasofino'},
            { text: 'Percheron', value: 'percheron'},
            { text: 'Peruvian Paso', value: 'peruvianpaso'},
            { text: 'Pony', value: 'pony'},
            { text: 'Pony of the Americas', value: 'ponyoftheamericas'},
            { text: 'Quarterhorse', value: 'quarterhorse'},
            { text: 'Rocky Mountain Horse', value: 'rockymountainhorse'},
            { text: 'Saddlebred', value: 'saddlebred'},
            { text: 'Shetland Pony', value: 'shetlandpony'},
            { text: 'Standardbred', value: 'standardbred'},
            { text: 'Tennessee Walker', value: 'tennesseewalker'},
            { text: 'Thoroughbred', value: 'thoroughbred'},
            { text: 'Warmblood', value: 'warmblood'},
        ];
    },
    getBreedsofBirds() {
        return [
            { text: 'African Grey', value: 'africangrey'},
            { text: 'Amazon', value: 'amazon'},
            { text: 'Brotogeris', value: 'brotogeris'},
            { text: 'Budgie / Budgerigar', value: 'budgiebudgerigar'},
            { text: 'Button-Quail', value: 'buttonquail'},
            { text: 'Caique', value: 'caique'},
            { text: 'Canary', value: 'canary'},
            { text: 'Chicken', value: 'chicken'},
            { text: 'Cockatiel', value: 'cockatiel'},
            { text: 'Cockatoo', value: 'cockatoo'},
            { text: 'Conure', value: 'conure'},
            { text: 'Dove', value: 'dove'},
            { text: 'Duck', value: 'duck'},
            { text: 'Eclectus', value: 'eclectus'},
            { text: 'Emu', value: 'emu'},
            { text: 'Finch', value: 'finch'},
            { text: 'Goose', value: 'goose'},
            { text: 'Guinea Fowl', value: 'guineafowl'},
            { text: 'Kakariki', value: 'kakariki'},
            { text: 'Lory / Lorikeet', value: 'lorylorikeet'},
            { text: 'Lovebird', value: 'lovebird'},
            { text: 'Macaw', value: 'macaw'},
            { text: 'Ostrich', value: 'ostrich'},
            { text: 'Parakeet', value: 'parakeet'},
            { text: 'Parrot', value: 'parrot'},
            { text: 'Parrotlet', value: 'parrotlet'},
            { text: 'Peacock / Peafowl', value: 'peacockpeafowl'},
            { text: 'Pheasant', value: 'pheasant'},
            { text: 'Pigeon', value: 'pigeon'},
            { text: 'Pionus', value: 'pionus'},
            { text: 'Poicephalus / Senegal', value: 'poicephalussenegal'},
            { text: 'Quail', value: 'quail'},
            { text: 'Quaker Parakeet', value: 'quakerparakeet'},
            { text: 'Rhea', value: 'rhea'},
            { text: 'Ringneck / Psittacula', value: 'ringneckpsittacula'},
            { text: 'Rosella', value: 'rosella'},
            { text: 'Swan', value: 'swan'},
            { text: 'Toucan', value: 'toucan'},
            { text: 'Turkey', value: 'turkey'},
        ];
    },
    getBreedsofOthers() {
        return [
            { text: 'Abyssinian', value: 'abyssinian'},
            { text: 'Alpaca', value: 'alpaca'},
            { text: 'Alpine', value: 'alpine'},
            { text: 'Angus', value: 'angus'},
            { text: 'Asian Box', value: 'asianbox'},
            { text: 'Ball Python', value: 'ballpython'},
            { text: 'Barbados', value: 'barbados'},
            { text: 'Bearded Dragon', value: 'beardeddragon'},
            { text: 'Boer', value: 'boer'},
            { text: 'Boa', value: 'boa'},
            { text: 'Boa Constrictor', value: 'boaconstrictor'},
            { text: 'Box', value: 'box'},
            { text: 'Bull', value: 'bull'},
            { text: 'Bullfrog', value: 'bullfrog'},
            { text: 'Burmese Python', value: 'burmesepython'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chinchilla', value: 'chinchilla'},
            { text: 'Corn / Rat', value: 'cornrat'},
            { text: 'Cow', value: 'cow'},
            { text: 'Degu', value: 'degu'},
            { text: 'Duroc', value: 'duroc'},
            { text: 'Dwarf Hamster', value: 'Dwarf Hamster'},
            { text: 'Eastern Box', value: 'Eastern Box'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chameleon', value: 'chameleon'},
            { text: 'Chameleon', value: 'chameleon'},
        ];
    }
}











