export default {

    getBreedOfDogs() {
        return [
            { text: '', value: ''},
            { text: 'Afghan Hound', value: 'Afghan Hound'},
            { text: 'Airedale Terrier', value: 'Airedale Terrier'},
            { text: 'Akbash', value: 'Akbash'},
            { text: 'Akita', value: 'Akita'},
            { text: 'Alaskan Malamute', value: 'Alaskan Malamute'},
            { text: 'American Bulldog', value: 'American Bulldog'},
            { text: 'American Bully', value: 'American Bully'},
            { text: 'American Eskimo Dog', value: 'American Eskimodog'},
            { text: 'American Foxhound', value: 'American Foxhound'},
            { text: 'American Hairless Terrier', value: 'American Hairless Terrier'},
            { text: 'American Staffordshire Terrier', value: 'American Staffordshire Terrier'},
            { text: 'American Water Spaniel', value: 'American Water Spaniel'},
            { text: 'Anatolian Shepherd', value: 'Anatolian Shepherd'},
            { text: 'Appenzell Mountain Dog', value: 'Appenzell Mountain Dog'},
            { text: 'Aussiedoodle', value: 'Aussiedoodle'},
            { text: 'Australian Cattle Dog / Blue Heeler', value: 'Australian Cattle Dog / Blue Heeler'},
            { text: 'Australian Kelpie', value: 'Australian Kelpie'},
            { text: 'Australian Shepherd', value: 'Australian Shepherd'},
            { text: 'Australian Terrier', value: 'Australian Terrier'},
            { text: 'Basenji', value: 'Basenji'},
            { text: 'Basset Hound', value: 'Basset Hound'},
            { text: 'Beagle', value: 'Beagle'},
            { text: 'Bearded Collie', value: 'Bearded Collie'},
            { text: 'Beauceron', value: 'Beauceron'},
            { text: 'Bedlington Terrier', value: 'Bedlington Terrier'},
            { text: 'Belgian Shepherd / Laekenois', value: 'Belgian Shepherd / Laekenois'},
            { text: 'Belgian Shepherd / Malinois', value: 'Belgian Shepherd / Malinois'},
            { text: 'Belgian Shepherd / Sheepdog', value: 'belgian Shepherd / Sheepdog'},
            { text: 'Belgian Shepherd / Tervuren', value: 'Belgian Shepherd / Tervuren'},
            { text: 'Bernedoodle', value: 'Bernedoodle'},
            { text: 'Bernese Mountain Dog', value: 'Bernese Mountain Dog'},
            { text: 'Bichon Frise', value: 'Bichon Frise'},
            { text: 'Black and Tan Coonhound', value: 'Black and Tan Coonhound'},
            { text: 'Black Labrador Retriever', value: 'Black Labrador Retriever'},
            { text: 'Black Mouth Cur', value: 'Black Mouth Cur'},
            { text: 'Bloodhound', value: 'Bloodhound'},
            { text: 'Blue Lacy', value: 'Blue Lacy'},
            { text: 'Bluetick Coonhound', value: 'Bluetick Coonhound'},
            { text: 'Boerboel', value: 'Boerboel'},
            { text: 'Bolognese', value: 'Bolognese'},
            { text: 'Border Collie', value: 'Border Collie'},
            { text: 'Border Terrier', value: 'Border Terrier'},
            { text: 'Borzoi', value: 'Borzoi'},
            { text: 'Boston Terrier', value: 'Boston Terrier'},
            { text: 'Bouvier des Flandres', value: 'Bouvier des Flandres'},
            { text: 'Boxer', value: 'Boxer'},
            { text: 'Boykin Spaniel', value: 'Boykin Spaniel'},
            { text: 'Briard', value: 'Briard'},
            { text: 'Brittany Spaniel', value: 'Brittany Spaniel'},
            { text: 'Brussels Griffon', value: 'Brussels Griffon'},
            { text: 'Bull Terrier', value: 'Bull Terrier'},
            { text: 'Bullmastiff', value: 'Bullmastiff'},
            { text: 'Cairn Terrier', value: 'Cairn Terrier'},
            { text: 'Canaan Dog', value: 'Canaan Dog'},
            { text: 'Cane Corso', value: 'Cane Corso'},
            { text: 'Cardigan Welsh Corgi', value: 'Cardigan Welsh Corgi'},
            { text: 'Carolina Dog', value: 'Carolina Dog'},
            { text: 'Catahoula Leopard Dog', value: 'Catahoula Leopard Dog'},
            { text: 'Cattle Dog', value: 'Cattledog'},
            { text: 'Caucasian Sheepdog / Caucasian Ovtcharka', value: 'Caucasian Sheepdog / Caucasian Ovtcharka'},
            { text: 'Cavalier King Charles Spaniel', value: 'Cavalier King Charles Spaniel'},
            { text: 'Cavapoo', value: 'Cavapoo'},
            { text: 'Chesapeake Bay Retriever', value: 'Chesapeake Bay Retriever'},
            { text: 'Chihuahua', value: 'Chihuahua'},
            { text: 'Chinese Crested Dog', value: 'Chinese Crested Dog'},
            { text: 'Chinese Foo Dog', value: 'Chinese Foo Dog'},
            { text: 'Chinook', value: 'Chinook'},
            { text: 'Chiweenie', value: 'Chiweenie'},
            { text: 'Chocolate Labrador Retriever', value: 'Chocolate Labrador Retriever'},
            { text: 'Chow Chow', value: 'Chow Chow'},
            { text: 'Cirneco dell Etna', value: 'Cirneco dell Etna'},
            { text: 'Clumber Spaniel', value: 'Clumber Spaniel'},
            { text: 'Cockapoo', value: 'Cockapoo'},
            { text: 'Cocker Spaniel', value: 'Cocker Spaniel'},
            { text: 'Collien', value: 'Collie'},
            { text: 'Coonhound', value: 'Coonhound'},
            { text: 'Corgi', value: 'Corgi'},
            { text: 'Coton de Tulear', value: 'Coton de Tulear'},
            { text: 'Curly-Coated Retriever', value: 'Curly-Coated Retriever'},
            { text: 'Dachshund', value: 'Dachshund'},
            { text: 'Dalmatian', value: 'Dalmatian'},
            { text: 'Dandie Dinmont Terrier', value: 'Dandie Dinmont Terrier'},
            { text: 'Doberman Pinscher', value: 'Doberman Pinscher'},
            { text: 'Dogo Argentino', value: 'Dogo Argentino'},
            { text: 'Dogue de Bordeaux', value: 'Dogue de Bordeaux'},
            { text: 'Dutch Shepherd', value: 'Dutch Shepherd'},
            { text: 'English Bulldog', value: 'English Bulldog'},
            { text: 'English Cocker Spaniel', value: 'English Cocker Spaniel'},
            { text: 'English Coonhound', value: 'English Coonhound'},
            { text: 'English Foxhound', value: 'English Foxhound'},
            { text: 'English Pointer', value: 'English Pointer'},
            { text: 'English Setter', value: 'English Setter'},
            { text: 'English Shepherd', value: 'English Shepherd'},
            { text: 'English Springer Spaniel', value: 'English Springer Spaniel'},
            { text: 'English Toy Spaniel', value: 'English Toy Spaniel'},
            { text: 'Eskimo Dog', value: 'Eskimo Dog'},
            { text: 'Feist', value: 'Feist'},
            { text: 'Field Spaniel', value: 'Field Spaniel'},
            { text: 'Fila Brasileiro', value: 'Fila Brasileiro'},
            { text: 'Finnish Lapphund', value: 'Finnish Lapphund'},
            { text: 'Finnish Spitz', value: 'Finnish Spitz'},
            { text: 'Flat-Coated Retriever', value: 'Flat-Coated Retriever'},
            { text: 'Fox Terrier', value: 'Fox Terrier'},
            { text: 'Foxhound', value: 'Foxhound'},
            { text: 'French Bulldog', value: 'French Bulldog'},
            { text: 'Galgo Spanish Greyhound', value: 'Galgo Spanish Greyhound'},
            { text: 'German Pinscher', value: 'German Pinscher'},
            { text: 'German Shepherd Dog', value: 'German Shepherd Dog'},
            { text: 'German Shorthaired Pointer', value: 'German Shorthaired Pointer'},
            { text: 'German Spitz', value: 'German Spitz'},
            { text: 'German Wirehaired Pointer', value: 'German Wirehaired Pointer'},
            { text: 'Giant Schnauzer', value: 'Giant Schnauzer'},
            { text: 'Glen of Imaal Terrier', value: 'Glen of Imaal Terrier'},
            { text: 'Golden Retriever', value: 'Golden Retriever'},
            { text: 'Goldendoodle', value: 'Goldendoodle'},
            { text: 'Gordon Setter', value: 'Gordon Setter'},
            { text: 'Great Dane', value: 'Great Dane'},
            { text: 'Great Pyrenees', value: 'Great Pyrenees'},
            { text: 'Greater Swiss Mountain Dog', value: 'Greater Swiss Mountain Dog'},
            { text: 'Greyhound', value: 'Greyhound'},
            { text: 'Hamiltonstovare', value: 'Hamiltonstovare'},
            { text: 'Harrier', value: 'Harrier'},
            { text: 'Havanese', value: 'Havanese'},
            { text: 'Hound', value: 'Hound'},
            { text: 'Hovawart', value: 'Hovawart'},
            { text: 'Husky', value: 'Husky'},
            { text: 'Ibizan Hound', value: 'Ibizanhound'},
            { text: 'Icelandic Sheepdog', value: 'Icelandic Sheepdog'},
            { text: 'Illyrian Sheepdog', value: 'Illyrian Sheepdog'},
            { text: 'Irish Setter', value: 'Irish setter'},
            { text: 'Irish Terrier', value: 'Irish Terrier'},
            { text: 'Irish Water Spaniel', value: 'Irish Water Spaniel'},
            { text: 'Irish Wolfhound', value: 'Irish Wolfhound'},
            { text: 'Italian Greyhound', value: 'Italian Greyhound'},
            { text: 'Jack Russell Terrier', value: 'Jack Russell Terrier'},
            { text: 'Japanese Chin', value: 'Japanese Chin'},
            { text: 'Jindo', value: 'Jindo'},
            { text: 'Kai Dog', value: 'Kaidog'},
            { text: 'Karelian Bear Dog', value: 'Karelian Bear Dog'},
            { text: 'Keeshond', value: 'Keeshond'},
            { text: 'Kerry Blue Terrier', value: 'Kerry Blue Terrier'},
            { text: 'Kishu', value: 'Kishu'},
            { text: 'Klee Kai', value: 'Klee Kai'},
            { text: 'Komondor', value: 'Komondor'},
            { text: 'Kuvasz', value: 'Kuvasz'},
            { text: 'Kyi Leo', value: 'Kyileo'},
            { text: 'Labradoodle', value: 'Labradoodle'},
            { text: 'Labrador Retriever', value: 'Labradorretriever'},
            { text: 'Lakeland Terrier', value: 'Lakelandterrier'},
            { text: 'Lancashire Heeler', value: 'Lancashireheeler'},
            { text: 'Leonberger', value: 'Leonberger'},
            { text: 'Lhasa Apso', value: 'Lhasaapso'},
            { text: 'Lowchen', value: 'Lowchen'},
            { text: 'Lurcher', value: 'Lurcher'},
            { text: 'Maltese', value: 'Maltese'},
            { text: 'Maltipoo', value: 'Maltipoo'},
            { text: 'Manchester Terrier', value: 'Manchester Terrier'},
            { text: 'Maremma Sheepdog', value: 'Maremma Sheepdog'},
            { text: 'Mastiff', value: 'Mastiff'},
            { text: 'McNab', value: 'McNab'},
            { text: 'Miniature Bull Terrier', value: 'Miniature Bull Terrier'},
            { text: 'Miniature Dachshund', value: 'Miniature Dachshund'},
            { text: 'Miniature Pinscher', value: 'Miniature Pinscher'},
            { text: 'Miniature Poodle', value: 'Miniature Poodle'},
            { text: 'Miniature Schnauzer', value: 'Miniature Schnauzer'},
            { text: 'Mixed Breed', value: 'Mixed Breed'},
            { text: 'Morkie', value: 'Morkie'},
            { text: 'Mountain Cur', value: 'Mountain Cur'},
            { text: 'Mountain Dog', value: 'Mountain Dog'},
            { text: 'Munsterlander', value: 'Munsterlander'},
            { text: 'Neapolitan Mastiff', value: 'Neapolitan Mastiff'},
            { text: 'New Guinea Singing Dog', value: 'New Guinea Singing Dog'},
            { text: 'Newfoundland Dog', value: 'Newfoundland Dog'},
            { text: 'Norfolk Terrier', value: 'Norfolk Terrier'},
            { text: 'Norwegian Buhund', value: 'Norwegian Buhund'},
            { text: 'Norwegian Elkhound', value: 'Norwegian Elkhound'},
            { text: 'Norwegian Lundehund', value: 'Norwegian Lundehund'},
            { text: 'Norwich Terrier', value: 'Norwich Terrier'},
            { text: 'Nova Scotia Duck Tolling Retriever', value: 'Nova Scotia Duck Tolling Retriever'},
            { text: 'Old English Sheepdog', value: 'Old English Sheepdog'},
            { text: 'Otterhound', value: 'Otterhound'},
            { text: 'Papillon', value: 'Papillon'},
            { text: 'Parson Russell Terrier', value: 'Parson Russell Terrier'},
            { text: 'Patterdale Terrier / Fell Terrier', value: 'Patterdale Terrier / Fell Terrier'},
            { text: 'Pekingese', value: 'Pekingese'},
            { text: 'Pembroke Welsh Corgi', value: 'Pembroke Welsh Corgi'},
            { text: 'Peruvian Inca Orchid', value: 'Peruvian Inca Orchid'},
            { text: 'Petit Basset Griffon Vendeen', value: 'Petit Basset Griffon Vendeen'},
            { text: 'Pharaoh Hound', value: 'Pharaoh Hound'},
            { text: 'Pit Bull Terrier', value: 'Pit Bull Terrier'},
            { text: 'Plott Hound', value: 'Plott Hound'},
            { text: 'Pointer', value: 'Pointer'},
            { text: 'Polish Lowland Sheepdog', value: 'Polish Lowland Sheepdog'},
            { text: 'Pomeranian', value: 'Pomeranian'},
            { text: 'Pomsky', value: 'Pomsky'},
            { text: 'Poodle', value: 'Poodle'},
            { text: 'Portuguese Podengo', value: 'Portuguese Podengo'},
            { text: 'Portuguese Water Dog', value: 'Portuguese Waterdog'},
            { text: 'Presa Canario', value: 'Presa Canario'},
            { text: 'Pug', value: 'Pug'},
            { text: 'Puggle', value: 'Puggle'},
            { text: 'Puli', value: 'Puli'},
            { text: 'Pumi', value: 'Pumi'},
            { text: 'Pyrenean Shepherd', value: 'Pyrenean Shepherd'},
            { text: 'Rat Terrier', value: 'Rat Terrier'},
            { text: 'Redbone Coonhound', value: 'Redbone Coonhound'},
            { text: 'Retriever', value: 'Retriever'},
            { text: 'Rhodesian Ridgeback', value: 'Rhodesian Ridgeback'},
            { text: 'Rottweiler', value: 'Rottweiler'},
            { text: 'Rough Collie', value: 'Rough Collie'},
            { text: 'Saint Bernard', value: 'Saint Bernard'},
            { text: 'Saluki', value: 'Saluki'},
            { text: 'Samoyed', value: 'Samoyed'},
            { text: 'Sarplaninac', value: 'Sarplaninac'},
            { text: 'Schipperke', value: 'Schipperke'},
            { text: 'Schnauzer', value: 'Schnauzer'},
            { text: 'Schnoodle', value: 'Schnoodle'},
            { text: 'Scottish Deerhound', value: 'Scottish Deerhound'},
            { text: 'Scottish Terrier', value: 'Scottish Terrier'},
            { text: 'Sealyham Terrier', value: 'Sealyham Terrier'},
            { text: 'Setter', value: 'Setter'},
            { text: 'Shar-Pei', value: 'Shar-Pei'},
            { text: 'Sheep Dog', value: 'Sheep Dog'},
            { text: 'Sheepadoodle', value: 'Sheepadoodle'},
            { text: 'Shepherd', value: 'Shepherd'},
            { text: 'Shetland Sheepdog / Sheltie', value: 'Shetland Sheepdog / Sheltie'},
            { text: 'Shiba Inu', value: 'Shiba Inu'},
            { text: 'Shih Poo', value: 'Shih Poo'},
            { text: 'Shih Tzu', value: 'Shih Tzu'},
            { text: 'Shollie', value: 'Shollie'},
            { text: 'Siberian Husky', value: 'Siberian Husky'},
            { text: 'Silky Terrier', value: 'Silky Terrier'},
            { text: 'Skye Terrier', value: 'Skye Terrier'},
            { text: 'Sloughi', value: 'Sloughi'},
            { text: 'Smooth Collie', value: 'Smooth Collie'},
            { text: 'Smooth Fox Terrier', value: 'Smooth Fox Terrier'},
            { text: 'South Russian Ovtcharka', value: 'South Russian Ovtcharka'},
            { text: 'Spaniel', value: 'Spaniel'},
            { text: 'Spanish Water Dog', value: 'Spanish Water Dog'},
            { text: 'Spinone Italiano', value: 'Spinone Italiano'},
            { text: 'Spitz', value: 'Spitz'},
            { text: 'Staffordshire Bull Terrier', value: 'Staffordshire Bull Terrier'},
            { text: 'Standard Poodle', value: 'Standard Poodle'},
            { text: 'Standard Schnauzer', value: 'Standard Schnauzer'},
            { text: 'Sussex Spaniel', value: 'Sussex Spaniel'},
            { text: 'Swedish Vallhund', value: 'Swedish Vallhund'},
            { text: 'Tennessee Treeing Brindle', value: 'Tennessee Treeing Brindle'},
            { text: 'Terrier', value: 'Terrier'},
            { text: 'Thai Ridgeback', value: 'Thai Ridgeback'},
            { text: 'Tibetan Mastiff', value: 'Tibetan Mastiff'},
            { text: 'Tibetan Spaniel', value: 'Tibetan Spaniel'},
            { text: 'Tibetan Terrier', value: 'Tibetan Terrier'},
            { text: 'Tosa Inu', value: 'Tosa Inu'},
            { text: 'Toy Fox Terrier', value: 'Toy Fox Terrier'},
            { text: 'Toy Manchester Terrier', value: 'Toy Manchester Terrier'},
            { text: 'Treeing Walker Coonhound', value: 'Treeing Walker Coonhound'},
            { text: 'Vizsla', value: 'Vizsla'},
            { text: 'Weimaraner', value: 'Weimaraner'},
            { text: 'Welsh Springer Spaniel', value: 'Welsh Springer Spaniel'},
            { text: 'Welsh Terrier', value: 'Welsh Terrier'},
            { text: 'West Highland White Terrier / Westie', value: 'West Highland White Terrier / Westie'},
            { text: 'Wheaten Terrier', value: 'Wheaten Terrier'},
            { text: 'Whippet', value: 'Whippet'},
            { text: 'White German Shepherd', value: 'White German Shepherd'},
            { text: 'Wire Fox Terrier', value: 'Wire Fox Terrier'},
            { text: 'Wirehaired Dachshund', value: 'Wirehaired Dachshund'},
            { text: 'Wirehaired Pointing Griffon', value: 'Wirehaired Pointing Griffon'},
            { text: 'Wirehaired Terrier', value: 'Wirehaired Terrier'},
            { text: 'Xoloitzcuintli / Mexican Hairless', value: 'Xoloitzcuintli / Mexican Hairless'},
            { text: 'Yellow Labrador Retriever', value: 'Yellow Labrador Retriever'},
            { text: 'Yorkshire Terrier', value: 'Yorkshire Terrier'},
        ];
    },
    getBreedsofCats() {
        return [
            { text: '', value: ''},
            { text: 'Abyssinian', value: 'Abyssinian'},
            { text: 'American Bobtail', value: 'American Bobtail'},
            { text: 'American Curl', value: 'American Curl'},
            { text: 'American Wirehair', value: 'American Wirehair'},
            { text: 'Applehead Siamese', value: 'Applehead Siamese'},
            { text: 'Balinese', value: 'Balinese'},
            { text: 'Bengal', value: 'Bengal'},
            { text: 'Birman', value: 'Birman'},
            { text: 'Bombay', value: 'Bombay'},
            { text: 'British Shorthair', value: 'British Shorthair'},
            { text: 'Burmese', value: 'Burmese'},
            { text: 'Burmilla', value: 'Burmilla'},
            { text: 'Calico', value: 'Calico'},
            { text: 'Canadian Hairless', value: 'Canadian Hairless'},
            { text: 'Chartreux', value: 'Hartreux'},
            { text: 'Chausie', value: 'Chausie'},
            { text: 'Chinchilla', value: 'Chinchilla'},
            { text: 'Cornish Rex', value: 'Cornishrex'},
            { text: 'Cymric', value: 'Cymric'},
            { text: 'Devon Rex', value: 'Dilutecalico'},
            { text: 'Dilute Tortoiseshell', value: 'Dilutetortoiseshell'},
            { text: 'Domestic Long Hair', value: 'Domestic Long Hair'},
            { text: 'Domestic Medium Hair', value: 'Domestic Medium Hair'},
            { text: 'Domestic Short Hair', value: 'Domestic Short Hair'},
            { text: 'Egyptian Mau', value: 'Egyptian Mau'},
            { text: 'Exotic Shorthair', value: 'Exotic Shorthair'},
            { text: 'Extra-Toes Cat / Hemingway Polydactyl', value: 'Extra-Toes Cat / Hemingway Polydactyl'},
            { text: 'Havana', value: 'Havana'},
            { text: 'Himalayan', value: 'Himalayan'},
            { text: 'Japanese Bobtail', value: 'Japanese Bobtail'},
            { text: 'Javanese', value: 'Javanese'},
            { text: 'Korat', value: 'Korat'},
            { text: 'LaPerm', value: 'Laperm'},
            { text: 'Maine Coon', value: 'Mainecoon'},
            { text: 'Manx', value: 'Manx'},
            { text: 'Nebelung', value: 'Nebelung'},
            { text: 'Norwegian Forest Cat', value: 'Norwegian Forest Cat'},
            { text: 'Ocicat', value: 'Ocicat'},
            { text: 'Oriental Long Hair', value: 'Oriental Long Hair'},
            { text: 'Oriental Short Hair', value: 'Oriental Short Hair'},
            { text: 'Oriental Tabby', value: 'Oriental Tabby'},
            { text: 'Persian', value: 'Persian'},
            { text: 'Pixiebob', value: 'Pixiebob'},
            { text: 'Ragamuffin', value: 'Ragamuffin'},
            { text: 'Ragdoll', value: 'Ragdoll'},
            { text: 'Russian Blue', value: 'Russian Blue'},
            { text: 'Scottish Fold', value: 'Scottish Fold'},
            { text: 'Selkirk Rex', value: 'Selkirk Rex'},
            { text: 'Siamese', value: 'Siamese'},
            { text: 'Siberian', value: 'Siberian'},
            { text: 'Silver', value: 'Silver'},
            { text: 'Singapura', value: 'Singapura'},
            { text: 'Snowshoe', value: 'Snowshoe'},
            { text: 'Somali', value: 'Somali'},
            { text: 'Sphynx / Hairless Cat', value: 'Sphynx / Hairless Cat'},
            { text: 'Tabby', value: 'Tabby'},
            { text: 'Tiger', value: 'Tiger'},
            { text: 'Tonkinese', value: 'Tonkinese'},
            { text: 'Torbie', value: 'Torbie'},
            { text: 'Tortoiseshell', value: 'Tortoiseshell'},
            { text: 'Toyger', value: 'Toyger'},
            { text: 'Turkish Angora', value: 'Turkishangora'},
            { text: 'Turkish Van', value: 'Turkishvan'},
            { text: 'Tuxedo', value: 'Tuxedo'},
            { text: 'York Chocolate', value: 'York Chocolate'},
        ];
    },
    getBreedsofRabbits() {
        return [
            { text: '', value: ''},
            { text: 'American', value: 'American'},
            { text: 'American Fuzzy Lop', value: 'American Fuzzy Lop'},
            { text: 'American Sable', value: 'American Sable'},
            { text: 'Angora Rabbit', value: 'Angora Rabbit'},
            { text: 'Belgian Hare', value: 'Belgian Hare'},
            { text: 'Beveren', value: 'Beveren'},
            { text: 'Britannia Petite', value: 'Britannia Petite'},
            { text: 'Bunny Rabbit', value: 'Bunny Rabbit'},
            { text: 'Californian', value: 'Californian'},
            { text: 'Champagne D Argent', value: 'Champagne D Argent'},
            { text: 'Checkered Giant', value: 'Checkered Giant'},
            { text: 'Chinchilla', value: 'Chinchilla'},
            { text: 'Cinnamon', value: 'Cinnamon'},
            { text: 'Creme D Argent', value: 'Creme D Argent'},
            { text: 'Dutch', value: 'Dutch'},
            { text: 'Dwarf', value: 'Dwarf'},
            { text: 'Dwarf Eared', value: 'Dwarf Eared'},
            { text: 'English Lop', value: 'English Lop'},
            { text: 'English Spot', value: 'English Spot'},
            { text: 'Flemish Giant', value: 'Flemish Giant'},
            { text: 'Florida White', value: 'Florida White'},
            { text: 'French Lop', value: 'French Lop'},
            { text: 'Havana', value: 'Havana'},
            { text: 'Himalayan', value: 'Himalayan'},
            { text: 'Holland Lop', value: 'hHlland Lop'},
            { text: 'Hotot', value: 'Hotot'},
            { text: 'Jersey Wooly', value: 'Jersey Wooly'},
            { text: 'Lilac', value: 'Lilac'},
            { text: 'Lionhead', value: 'Lionhead'},
            { text: 'Lop Eared', value: 'Lop Eared'},
            { text: 'Mini Lop', value: 'Mini Lop'},
            { text: 'Mini Rex', value: 'Mini Rex'},
            { text: 'Netherland Dwarf', value: 'Netherland Dwarf'},
            { text: 'Mini Rex', value: 'New Zealand'},
            { text: 'Palomino', value: 'Palomino'},
            { text: 'Polish', value: 'Polish'},
            { text: 'Rex', value: 'Rex'},
            { text: 'Rhinelander', value: 'Rhinelander'},
            { text: 'Satin', value: 'Satin'},
            { text: 'Silver', value: 'Silver'},
            { text: 'Silver Fox', value: 'Silver Fox'},
            { text: 'Silver Marten', value: 'Silver Marten'},
            { text: 'Tan', value: 'Tan'},
        ];
    },
    getBreedsofHorse() {
        return [
            { text: '', value: ''},
            { text: 'Appaloosa', value: 'Appaloosa'},
            { text: 'Arabian', value: 'Arabian'},
            { text: 'Belgian', value: 'Belgian'},
            { text: 'Clydesdale', value: 'Clydesdale'},
            { text: 'Connemara', value: 'Connemara'},
            { text: 'Curly Horse', value: 'Curly Horse'},
            { text: 'Donkey', value: 'Donkey'},
            { text: 'Draft', value: 'Draft'},
            { text: 'Friesian', value: 'Friesian'},
            { text: 'Gaited', value: 'Gaited'},
            { text: 'Grade', value: 'Grade'},
            { text: 'Haflinger', value: 'Haflinger'},
            { text: 'Icelandic Horse', value: 'Icelandic Horse'},
            { text: 'Lipizzan', value: 'Lipizzan'},
            { text: 'Miniature Horse', value: 'Miniature Horse'},
            { text: 'Missouri Foxtrotter', value: 'Missouri Foxtrotter'},
            { text: 'Morgan', value: 'Morgan'},
            { text: 'Mule', value: 'Mule'},
            { text: 'Mustang', value: 'Mustang'},
            { text: 'Paint / Pinto', value: 'Paint / Pinto'},
            { text: 'Palomino', value: 'Palomino'},
            { text: 'Paso Fino', value: 'Paso Fino'},
            { text: 'Percheron', value: 'Percheron'},
            { text: 'Peruvian Paso', value: 'Peruvian Paso'},
            { text: 'Pony', value: 'Pony'},
            { text: 'Pony of the Americas', value: 'Pony of the Americas'},
            { text: 'Quarterhorse', value: 'Quarterhorse'},
            { text: 'Rocky Mountain Horse', value: 'Rocky Mountain Horse'},
            { text: 'Saddlebred', value: 'Saddlebred'},
            { text: 'Shetland Pony', value: 'Shetland Pony'},
            { text: 'Standardbred', value: 'Standardbred'},
            { text: 'Tennessee Walker', value: 'Tennessee Walker'},
            { text: 'Thoroughbred', value: 'Thoroughbred'},
            { text: 'Warmblood', value: 'Warmblood'},
        ];
    },
    getBreedsofBirds() {
        return [
            { text: '', value: ''},
            { text: 'African Grey', value: 'African Grey'},
            { text: 'Amazon', value: 'Amazon'},
            { text: 'Brotogeris', value: 'Brotogeris'},
            { text: 'Budgie / Budgerigar', value: 'Budgie / Budgerigar'},
            { text: 'Button-Quail', value: 'Button-Quail'},
            { text: 'Caique', value: 'Caique'},
            { text: 'Canary', value: 'Canary'},
            { text: 'Chicken', value: 'Chicken'},
            { text: 'Cockatiel', value: 'Cockatiel'},
            { text: 'Cockatoo', value: 'Cockatoo'},
            { text: 'Conure', value: 'Conure'},
            { text: 'Dove', value: 'Dove'},
            { text: 'Duck', value: 'Duck'},
            { text: 'Eclectus', value: 'Eclectus'},
            { text: 'Emu', value: 'Emu'},
            { text: 'Finch', value: 'Finch'},
            { text: 'Goose', value: 'Goose'},
            { text: 'Guinea Fowl', value: 'Guinea Fowl'},
            { text: 'Kakariki', value: 'Kakariki'},
            { text: 'Lory / Lorikeet', value: 'Lory / Lorikeet'},
            { text: 'Lovebird', value: 'Lovebird'},
            { text: 'Macaw', value: 'Macaw'},
            { text: 'Ostrich', value: 'Ostrich'},
            { text: 'Parakeet', value: 'Parakeet'},
            { text: 'Parrot', value: 'Parrot'},
            { text: 'Parrotlet', value: 'Parrotlet'},
            { text: 'Peacock / Peafowl', value: 'Peacock / Peafowl'},
            { text: 'Pheasant', value: 'Pheasant'},
            { text: 'Pigeon', value: 'Pigeon'},
            { text: 'Pionus', value: 'Pionus'},
            { text: 'Poicephalus / Senegal', value: 'Poicephalus / Senegal'},
            { text: 'Quail', value: 'Quail'},
            { text: 'Quaker Parakeet', value: 'Quaker Parakeet'},
            { text: 'Rhea', value: 'Rhea'},
            { text: 'Ringneck / Psittacula', value: 'Ringneck / Psittacula'},
            { text: 'Rosella', value: 'Rosella'},
            { text: 'Swan', value: 'Swan'},
            { text: 'Toucan', value: 'Toucan'},
            { text: 'Turkey', value: 'Turkey'},
        ];
    },
    getBreedsofOthers() {
        return [
            { text: '', value: ''},
            { text: 'Alpaca', value: 'Alpaca'},
            { text: 'Alpine', value: 'Alpine'},
            { text: 'Angus', value: 'Angus'},
            { text: 'Asian Box', value: 'Asian Box'},
            { text: 'Ball Python', value: 'Ball Python'},
            { text: 'Barbados', value: 'Barbados'},
            { text: 'Bearded Dragon', value: 'Bearded Dragon'},
            { text: 'Boer', value: 'Boer'},
            { text: 'Boa', value: 'Boa'},
            { text: 'Boa Constrictor', value: 'Boa Constrictor'},
            { text: 'Box', value: 'Box'},
            { text: 'Bull', value: 'Bull'},
            { text: 'Bullfrog', value: 'Bullfrog'},
            { text: 'Burmese Python', value: 'Burmese Python'},
            { text: 'Chameleon', value: 'Chameleon'},
            { text: 'Chinchilla', value: 'Chinchilla'},
            { text: 'Corn / Rat', value: 'Corn / Rat'},
            { text: 'Cow', value: 'Cow'},
            { text: 'Degu', value: 'Degu'},
            { text: 'Duroc', value: 'Duroc'},
            { text: 'Dwarf Hamster', value: 'Dwarf Hamster'},
            { text: 'Eastern Box', value: 'Eastern Box'},
            { text: 'Ferret', value: 'Ferret'},
            { text: 'Fire Salamander', value: 'firesalamander'},
            { text: 'Fire-Bellied', value: 'Fire-Bellied'},
            { text: 'Fire-Bellied Newt', value: 'Fire-Bellied Newt'},
            { text: 'Florida Box', value: 'Florida Box'},
            { text: 'Freshwater Fish', value: 'Freshwater Fish'},
            { text: 'Frog', value: 'Frog'},
            { text: 'Garter / Ribbon', value: 'Garter / Ribbon'},
            { text: 'Gecko', value: 'Gecko'},
            { text: 'Gerbil', value: 'Gerbil'},
            { text: 'Goat', value: 'Goat'},
            { text: 'Goldfish', value: 'Goldfish'},
            { text: 'Guinea Pig', value: 'Guinea Pig'},
            { text: 'Hampshire', value: 'Hampshire'},
            { text: 'Hamster', value: 'Hamster'},
            { text: 'Hedgehog', value: 'Hedgehog'},
            { text: 'Hermit Crab', value: 'Hermit Crab'},
            { text: 'holstein', value: 'Holstein'},
            { text: 'Horned Frog', value: 'Hornedfrog'},
            { text: 'Iguana', value: 'Iguana'},
            { text: 'Jersey', value: 'Jersey'},
            { text: 'King / Milk', value: 'King / Milk'},
            { text: 'LaMancha', value: 'LaMancha'},
            { text: 'Landrace', value: 'Landrace'},
            { text: 'Leopard', value: 'Leopard'},
            { text: 'Leopard Frog', value: 'Leopard Frog'},
            { text: 'Lizard', value: 'Lizard'},
            { text: 'Llama', value: 'Llama'},
            { text: 'Merino', value: 'Merino'},
            { text: 'Mississippi Map Turtle', value: 'Mississippi Map Turtle'},
            { text: 'Monitor', value: 'Monitor'},
            { text: 'Mouflon', value: 'Mouflon'},
            { text: 'Mouse', value: 'Mouse'},
            { text: 'Mud', value: 'Mud'},
            { text: 'Musk', value: 'Musk'},
            { text: 'Myotonic / Fainting', value: 'Myotonic/ Fainting'},
            { text: 'Nigerian Dwarf', value: 'Nigerian Dwarf'},
            { text: 'Nubian', value: 'Nubian'},
            { text: 'Oberhasli', value: 'Oberhasli'},
            { text: 'Oregon Newt', value: 'Oregon Newt'},
            { text: 'Ornamental Box', value: 'Ornamental Box'},
            { text: 'Other', value: 'Other'},
            { text: 'Paddle Tailed Newt', value: 'Paddle Tailed Newt'},
            { text: 'Painted', value: 'Painted'},
            { text: 'Peruvian', value: 'Peruvian'},
            { text: 'Pig', value: 'Pig'},
            { text: 'Pot Bellied', value: 'Pot Bellied'},
            { text: 'Prairie Dog', value: 'Prairie Dog'},
            { text: 'Pygmy', value: 'Pygmy'},
            { text: 'Python', value: 'Python'},
            { text: 'Rat', value: 'Rat'},
            { text: 'Red Foot', value: 'Red Foot'},
            { text: 'Red-Eared Slider', value: 'Red-Eared Slider'},
            { text: 'Rex', value: 'Rex'},
            { text: 'Russian', value: 'Russian'},
            { text: 'Saanen', value: 'Saanen'},
            { text: 'Saltwater Fish', value: 'Saltwater Fish'},
            { text: 'Scorpion', value: 'Scorpion'},
            { text: 'Sheep', value: 'Sheep'},
            { text: 'Shetland', value: 'Shetland'},
            { text: 'Short-Haired', value: 'Short-Haired'},
            { text: 'Silkie / Sheltie', value: 'Silkie / Sheltie'},
            { text: 'Skunk', value: 'Skunk'},
            { text: 'Snake', value: 'Snake'},
            { text: 'Snapping', value: 'Snapping'},
            { text: 'Soft Shell', value: 'Soft Shell'},
            { text: 'Southern', value: 'Southern'},
            { text: 'Sugar Glider', value: 'Sugar Glider'},
            { text: 'Sulcata', value: 'Sulcata'},
            { text: 'Tarantula', value: 'Tarantula'},
            { text: 'Teddy', value: 'Teddy'},
            { text: 'Three-Toed Box', value: 'Three-Toed Box'},
            { text: 'Tiger Salamander', value: 'Tiger Salamander'},
            { text: 'Toad', value: 'Toad'},
            { text: 'Toggenburg', value: 'Toggenburg'},
            { text: 'Tortoise', value: 'Tortoise'},
            { text: 'Tree Frog', value: 'Treefrog'},
            { text: 'Turtle', value: 'Turtle'},
            { text: 'Uromastyx', value: 'Uromastyx'},
            { text: 'Vietnamese Pot Bellied', value: 'Vietnamese Potbellied'},
            { text: 'Water Dragon', value: 'Water Dragon'},
            { text: 'Yellow-Bellied Slider', value: 'Yellow-Bellied Slider'},
            { text: 'Yorkshire', value: 'Yorkshire'},
        ];
    }
}











